site_name: Ultimate Guide to UAA by Stark & Wayne
pages:
  - Introduction: index.md
  - Install uaa CLI: install-cli.md
  - Deploy UAA: deploy-uaa.md
  - UAA and Client Apps: uaa-and-client-apps.md
  - Users: users.md
  - Authenticating User with Password: authenticating-user-via-password.md
  - Authenticating User via Web UI: authenticating-user-via-authcode.md
  - User Permissions: user-permissions.md
  - Client Permissions: client-permissions.md

theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

  logo: 'images/favicon/favicon-64.png'

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix the tutorials'
repo_url: 'https://github.com/starkandwayne/uaa-deployment'
edit_uri: edit/master/docs/
extra_css: [print.css]
# google_analytics: ['UA-50822525-6', 'concoursetutorial.com']
