---
meta:
  name:    uaa-deployment
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  aws:
    region_name: us-east-2
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))
    cloudfront_url: https://cdn-cfcommunity.starkandwayne.com

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  github:
    owner:  starkandwayne
    repo:   (( grab meta.pipeline ))
    branch: develop
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  bosh:
    target:   ((bosh-lite-environment))
    cacert:   ((bosh-lite-ca-cert))
    username: ((bosh-lite-client))
    password: ((bosh-lite-client-secret))

  slack:
    webhook:  ((slack-webhook))
    icon:     ((slack-logo))
    username: ((slack-username))